--liquibase formatted sql
--changeset author:kamyshev_1.1.0

ALTER TABLE CLIENT ADD PREV_NAME VARCHAR2(25);
UPDATE CLIENT SET PREV_NAME = 'PREV_TEST_1' WHERE ID = 1;
UPDATE CLIENT SET PREV_NAME = 'PREV_TEST_2' WHERE ID = 2;
UPDATE CLIENT SET PREV_NAME = 'PREV_TEST_3' WHERE ID = 3;
COMMIT;